Repository submariner-io/lighthouse, pull requests merged in 2020-10, with the labels that each got.

#314 Link to general contributing docs vs LH-specific
  README.md
Labels: cncf, documentation

#310 Add build Make target for building both binaries
  Makefile
Labels: automation, cncf, documentation

#321 Update codeowners in lighthouse
  CODEOWNERS
Labels: cncf

#325 Refactor linting GHA jobs/workflows
  .github/workflows/dco-check.yml
  .github/workflows/gitlint.yml
  .github/workflows/linting.yml
  .github/workflows/md-links.yml
  .github/workflows/yaml-lint.yml
Labels: automation, cncf, documentation

#328 Refactor E2E GHA workflow
  .github/workflows/e2e.yml
Labels: automation, cncf, documentation

#326 Refactor unit test job
  .github/workflows/unit.yml
  .github/workflows/validations.yml
  Makefile
Labels: automation, cncf, documentation

#327 Refactor periodic GHA workflow
  .github/workflows/periodic.yml
Labels: automation, cncf, documentation

#330 Remove code-gen job
  .github/workflows/linting.yml
Labels: automation, bug

#329 Refactor release job
  .github/workflows/release.yml
Labels: automation, cncf, documentation

#359 Use TargetRef for hostname
  pkg/agent/controller/endpoint.go
Labels: bug
