Repository submariner-io/lighthouse, pull requests merged in 2021-05, with the labels that each got.

#532 Don't run certain GHA jobs on forks
  .github/workflows/flake_finder.yml
  .github/workflows/periodic.yml
  .github/workflows/release.yml
Labels: automation

#533 Run full E2E matrix only when PR approved
  .github/workflows/e2e-full.yml
  .github/workflows/e2e.yml
  .github/workflows/label-ready-approved.yml
Labels: ready-to-test

#538 Add CII badge, remove PR-triggered badges
  README.md
Labels: cncf, documentation, ready-to-test

#541 Add pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cncf, documentation, ready-to-test

#540 Don't label when approved
  .github/workflows/label-ready-approved.yml
Labels: ready-to-test

#539 Update the copyright statements to match CNCF recs
  .github/workflows/linting.yml
  .licenserc.json
  pkg/agent/controller/agent.go
  pkg/agent/controller/agent_test.go
  pkg/agent/controller/controller_suite_test.go
  pkg/agent/controller/endpoint.go
  pkg/agent/controller/serviceimport.go
  pkg/agent/controller/types.go
  pkg/agent/main.go
  pkg/constants/constants.go
  pkg/coredns/main.go
  pkg/endpointslice/controller.go
  pkg/endpointslice/controller_test.go
  pkg/endpointslice/map.go
  pkg/endpointslice/map_test.go
  pkg/endpointslice/store.go
  pkg/endpointslice/suite_test.go
  pkg/gateway/controller.go
  pkg/gateway/controller_test.go
  pkg/service/controller.go
  pkg/serviceimport/controller.go
  pkg/serviceimport/controller_test.go
  pkg/serviceimport/map.go
  pkg/serviceimport/map_test.go
  pkg/serviceimport/store.go
  pkg/serviceimport/suite_test.go
  plugin/lighthouse/handler.go
  plugin/lighthouse/handler_test.go
  plugin/lighthouse/lighthouse.go
  plugin/lighthouse/parse.go
  plugin/lighthouse/parse_test.go
  plugin/lighthouse/plugin_suite_test.go
  plugin/lighthouse/setup.go
  plugin/lighthouse/setup_test.go
  test/e2e/discovery/headless_services.go
  test/e2e/discovery/service_discovery.go
  test/e2e/discovery/statefulsets.go
  test/e2e/e2e_test.go
  test/e2e/framework/framework.go
Labels: ready-to-test

#542 Add bot config for labelling when approved
  .submarinerbot.yaml
Labels: ready-to-test

#545 Don't run E2E on push
  .github/workflows/release.yml
Labels: ready-to-test

#546 Use shared GHA to release images
  .github/workflows/release.yml
Labels: ready-to-test
