Repository submariner-io/lighthouse, pull requests merged in 2021-08, with the labels that each got.

#596 Don't run periodic PR dependency checks on forks
  .github/workflows/dependent-issues.yml
Labels: automation, ready-to-test

#606 Fix YAML linting errors
  .github/dependabot.yml
  .github/workflows/dependent-issues.yml
  .golangci.yml
  .lichen.yaml
  .submarinerbot.yaml
Labels: bug, automation, ready-to-test

#594 LH Load Balancing logic
  pkg/loadbalancer/balancer.go
  pkg/loadbalancer/smooth_weighted_round_robin.go
  pkg/loadbalancer/smooth_weighted_round_robin_test.go
  pkg/loadbalancer/suite_test.go
  pkg/serviceimport/map.go
Labels: ready-to-test

#609 Remove non-functional yamllint strict config
  .yamllint.yml
Labels: automation, ready-to-test

#610 Revert to a r/w version of dependent-issues
  .github/workflows/dependent-issues.yml
Labels: ready-to-test
