Repository submariner-io/lighthouse, pull requests merged in 2021-01, with the labels that each got.

#425 Add license headers to Go files
  pkg/agent/controller/agent.go
  pkg/agent/controller/agent_test.go
  pkg/agent/controller/controller_suite_test.go
  pkg/agent/controller/endpoint.go
  pkg/agent/controller/lhserviceexport.go
  pkg/agent/controller/lhserviceexport_test.go
  pkg/agent/controller/serviceimport.go
  pkg/agent/controller/types.go
  pkg/agent/main.go
  pkg/apis/lighthouse.submariner.io/v2alpha1/doc.go
  pkg/apis/lighthouse.submariner.io/v2alpha1/register.go
  pkg/apis/lighthouse.submariner.io/v2alpha1/types.go
  pkg/constants/constants.go
  pkg/coredns/main.go
  pkg/endpointslice/controller.go
  pkg/endpointslice/controller_test.go
  pkg/endpointslice/map.go
  pkg/endpointslice/map_test.go
  pkg/endpointslice/store.go
  pkg/endpointslice/suite_test.go
  pkg/gateway/controller.go
  pkg/gateway/controller_test.go
  pkg/service/controller.go
  pkg/serviceimport/controller.go
  pkg/serviceimport/controller_test.go
  pkg/serviceimport/map.go
  pkg/serviceimport/map_test.go
  pkg/serviceimport/store.go
  pkg/serviceimport/suite_test.go
  plugin/lighthouse/handler.go
  plugin/lighthouse/handler_test.go
  plugin/lighthouse/lighthouse.go
  plugin/lighthouse/parse.go
  plugin/lighthouse/parse_test.go
  plugin/lighthouse/plugin_suite_test.go
  plugin/lighthouse/setup.go
  plugin/lighthouse/setup_test.go
  test/e2e/discovery/headless_services.go
  test/e2e/discovery/service_discovery.go
  test/e2e/discovery/statefulsets.go
  test/e2e/e2e_test.go
  test/e2e/framework/framework.go
Labels: cncf

#430 Fix issues in e2e
  test/e2e/discovery/service_discovery.go
Labels: backport

#429 E2e to verify lighthouse return cluster-ip from healthy service
  test/e2e/discovery/service_discovery.go
  test/e2e/framework/framework.go
Labels: backport

#435 Use the PR base branch as reference when linting
  .github/workflows/linting.yml
Labels: backport

#437 Remove Lighthouse-specific ServiceImport/Export
  pkg/agent/controller/agent.go
  pkg/agent/controller/agent_test.go
  pkg/agent/controller/controller_suite_test.go
  pkg/agent/controller/endpoint.go
  pkg/agent/controller/lhserviceexport.go
  pkg/agent/controller/lhserviceexport_test.go
  pkg/agent/controller/types.go
  pkg/agent/main.go
  pkg/apis/lighthouse.submariner.io/v2alpha1/doc.go
  pkg/apis/lighthouse.submariner.io/v2alpha1/register.go
  pkg/apis/lighthouse.submariner.io/v2alpha1/types.go
  pkg/apis/lighthouse.submariner.io/v2alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/doc.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/doc.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/doc.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/lighthouse.submariner.io/v2alpha1/doc.go
  pkg/client/clientset/versioned/typed/lighthouse.submariner.io/v2alpha1/fake/doc.go
  pkg/client/clientset/versioned/typed/lighthouse.submariner.io/v2alpha1/fake/fake_lighthouse.submariner.io_client.go
  pkg/client/clientset/versioned/typed/lighthouse.submariner.io/v2alpha1/fake/fake_serviceexport.go
  pkg/client/clientset/versioned/typed/lighthouse.submariner.io/v2alpha1/fake/fake_serviceimport.go
  pkg/client/clientset/versioned/typed/lighthouse.submariner.io/v2alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/lighthouse.submariner.io/v2alpha1/lighthouse.submariner.io_client.go
  pkg/client/clientset/versioned/typed/lighthouse.submariner.io/v2alpha1/serviceexport.go
  pkg/client/clientset/versioned/typed/lighthouse.submariner.io/v2alpha1/serviceimport.go
  pkg/client/informers/externalversions/factory.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/client/informers/externalversions/lighthouse.submariner.io/interface.go
  pkg/client/informers/externalversions/lighthouse.submariner.io/v2alpha1/interface.go
  pkg/client/informers/externalversions/lighthouse.submariner.io/v2alpha1/serviceexport.go
  pkg/client/informers/externalversions/lighthouse.submariner.io/v2alpha1/serviceimport.go
  pkg/client/listers/lighthouse.submariner.io/v2alpha1/expansion_generated.go
  pkg/client/listers/lighthouse.submariner.io/v2alpha1/serviceexport.go
  pkg/client/listers/lighthouse.submariner.io/v2alpha1/serviceimport.go
  scripts/codegen
Labels: mcs-api-alignment
