Repository submariner-io/lighthouse, pull requests merged in 2022-08, with the labels that each got.

#841 Run SonarScan, publish unit results and coverage
  .github/workflows/report.yml
  sonar-project.properties
Labels: ready-to-test, maintenance

#843 Sonar-report coredns mod coverage, ignore e2e
  sonar-project.properties
Labels: ready-to-test, maintenance

#844 Fix typo in E2E test descriptions
  test/e2e/discovery/headless_services.go
  test/e2e/discovery/statefulsets.go
Labels: bug, ready-to-test

#839 Use ENV vars instead of flags
  Makefile
Labels: ready-to-test

#845 Set ReadHeaderTimeout to 60s to mitigate Slowloris
  pkg/agent/main.go
Labels: bug, ready-to-test

#852 Require Go 1.18
  coredns/go.mod
  coredns/go.sum
  go.mod
Labels: ready-to-test

#821 Remove all possible GitHub Action permissions
  .github/workflows/branch.yml
  .github/workflows/codeowners.yml
  .github/workflows/dependent-issues.yml
  .github/workflows/e2e-full.yml
  .github/workflows/e2e.yml
  .github/workflows/flake_finder.yml
  .github/workflows/linting.yml
  .github/workflows/multiarch.yml
  .github/workflows/periodic.yml
  .github/workflows/release.yml
  .github/workflows/report.yml
  .github/workflows/unit.yml
  .github/workflows/upgrade-e2e.yml
Labels: ready-to-test

#858 Restore some permissions for dependent issues GHA
  .github/workflows/dependent-issues.yml
Labels: ready-to-test

#861 Add security-events write permission for reporting
  .github/workflows/report.yml
Labels: ready-to-test

#863 Check GHA updates weekly
  .github/dependabot.yml
Labels: ready-to-test

#860 If no service matches a DNS request, return empty
  coredns/plugin/handler.go
  coredns/plugin/handler_test.go
Labels: bug, ready-to-test, release-note-needed
