Repository submariner-io/lighthouse, pull requests merged in 2022-05, with the labels that each got.

#732 Add Dependabot updates of GitHub Actions
  .github/dependabot.yml
Labels: ready-to-test, maintenance

#737 Use new nettest simpleserver from Shipyard
  test/e2e/framework/framework.go
Labels: bug, backport, ready-to-test

#748 Backport: Use Shipyard's nettest simpleserver
  test/e2e/framework/framework.go
Labels: bug, ready-to-test, automated-backport

#749 Bump markdown-link-check to the current tip
  .github/workflows/linting.yml
  .github/workflows/periodic.yml
Labels: ready-to-test

#746 Build packages, not files
  Makefile
Labels: ready-to-test

#756 Ignore coredns/vendor in yamllint
  .yamllint.yml
Labels: ready-to-test, maintenance

#762 Move controllers used by plugin to coredns
  coredns/endpointslice/controller.go
  coredns/endpointslice/controller_test.go
  coredns/endpointslice/map.go
  coredns/endpointslice/map_test.go
  coredns/endpointslice/suite_test.go
  coredns/gateway/controller.go
  coredns/gateway/controller_test.go
  coredns/go.mod
  coredns/plugin/handler.go
  coredns/plugin/handler_test.go
  coredns/plugin/lighthouse.go
  coredns/plugin/record.go
  coredns/plugin/setup.go
  coredns/plugin/setup_internal_test.go
  coredns/service/controller.go
  coredns/serviceimport/controller.go
  coredns/serviceimport/controller_test.go
  coredns/serviceimport/map.go
  coredns/serviceimport/map_test.go
  coredns/serviceimport/store.go
  coredns/serviceimport/suite_test.go
Labels: ready-to-test

#759 Require Go 1.17
  go.mod
  go.sum
Labels: ready-to-test

#761 Bump github.com/prometheus/client_golang from 1.12.1 to 1.12.2
  coredns/go.mod
  coredns/go.sum
  go.mod
  go.sum
Labels: ready-to-test

#763 Automated backport of #749: Bump markdown-link-check to the current tip
  .github/workflows/linting.yml
  .github/workflows/periodic.yml
Labels: automated-backport

#764 Use Dependabot to update GHAs on release-0.12
  .github/dependabot.yml
Labels: ready-to-test, maintenance

#774 Bump Admiral to 0.13.0-m2
  coredns/go.mod
  coredns/go.sum
  go.mod
  go.sum
Labels: ready-to-test
