Repository submariner-io/lighthouse, pull requests merged in 2022-10, with the labels that each got.

#893 Remove helm jobs
  .github/workflows/e2e-full.yml
  Makefile
Labels: ready-to-test

#905 Automated backport of #880: Use the default kind CNI
  .shipyard.e2e.yml
Labels: ready-to-test, automated-backport

#904 Automated backport of #880: Use the default kind CNI
  .shipyard.e2e.yml
Labels: ready-to-test, automated-backport

#906 Update x/text to latest, fixes CVE-2022-32149
  coredns/go.mod
  coredns/go.sum
  go.mod
  go.sum
Labels: ready-to-test, backport-needed

#911 Sonar shallow clone, remove debug
  .github/workflows/report.yml
Labels: automation, ready-to-test

#913 Add issues:write permission to broken links GHA
  .github/workflows/periodic.yml
Labels: automation, ready-to-test

#914 Remove space between // and nolint
  coredns/endpointslice/controller.go
  coredns/endpointslice/map_test.go
  coredns/gateway/controller.go
  coredns/plugin/handler.go
  coredns/plugin/handler_test.go
  coredns/plugin/setup.go
  coredns/service/controller.go
  coredns/serviceimport/controller.go
  coredns/serviceimport/controller_test.go
  pkg/agent/controller/agent.go
  pkg/agent/controller/cleanup.go
  pkg/agent/controller/controller_suite_test.go
  pkg/agent/controller/global_ingressip_cache.go
  test/e2e/discovery/headless_services.go
  test/e2e/discovery/service_discovery.go
  test/e2e/discovery/statefulsets.go
Labels: ready-to-test

#916 Use NormalizeExact instead of the deprecated Normalize
  coredns/plugin/setup.go
Labels: ready-to-test

#927 Revert "Make lighthouse depend on coredns"
  coredns/constants/constants.go
  coredns/endpointslice/controller.go
  coredns/endpointslice/controller_test.go
  coredns/endpointslice/map.go
  coredns/endpointslice/map_test.go
  coredns/go.mod
  coredns/plugin/handler_test.go
  coredns/serviceimport/controller_test.go
  coredns/serviceimport/map.go
  go.mod
  go.sum
  pkg/agent/controller/agent.go
  pkg/agent/controller/cleanup.go
  pkg/agent/controller/cleanup_test.go
  pkg/agent/controller/controller_suite_test.go
  pkg/agent/controller/endpoint.go
  pkg/agent/controller/serviceimport.go
  pkg/constants/constants.go
  pkg/loadbalancer/balancer.go
  pkg/loadbalancer/smooth_weighted_round_robin.go
  pkg/loadbalancer/smooth_weighted_round_robin_test.go
  pkg/loadbalancer/suite_test.go
  test/e2e/discovery/statefulsets.go
  test/e2e/framework/framework.go
Labels: ready-to-test

#935 Don't use local lighthouse in coredns go.mod
  coredns/go.mod
  coredns/go.sum
Labels: ready-to-test
