Repository submariner-io/lighthouse, pull requests merged in 2022-07, with the labels that each got.

#793 fix spell problem MultiCluster was spelled as MutliCluster
  test/e2e/discovery/service_discovery.go
Labels: ready-to-test

#799 Bump the coredns module to Go 1.17
  coredns/go.mod
  coredns/go.sum
Labels: ready-to-test

#796 Enable Dependabot for coredns go module
  .github/dependabot.yml
Labels: ready-to-test

#807 Bump x/text to address CVE-2021-38561
  coredns/go.mod
  coredns/go.sum
  go.mod
  go.sum
Labels: backport, ready-to-test

#810 Pin Admiral to v0.13.0-rc2
  coredns/go.mod
  coredns/go.sum
  go.mod
  go.sum
Labels: ready-to-test

#805 Update coredns dependabot config
  .github/dependabot.yml
Labels: ready-to-test

#812 Bump coredns module to K8s v0.24.2
  coredns/go.mod
  coredns/go.sum
Labels: ready-to-test

#798 Add Anchore vulnerability scanning, publish SARIF
  .github/workflows/linting.yml
  .grype.yaml
Labels: ready-to-test

#814 Rely on CoreDNS caddy only
  coredns/go.mod
  coredns/go.sum
  coredns/main.go
Labels: ready-to-test

#820 Fail Anchore vuln scans on PRs
  .github/workflows/linting.yml
Labels: ready-to-test, maintenance

#825 Don't use local lighthouse in coredns go.mod
  coredns/go.mod
  coredns/go.sum
Labels: ready-to-test, maintenance

#828 Use minimal KIND clusters
  .shipyard.e2e.yml
Labels: ready-to-test

#834 Run the upgrade job on devel only
  .github/workflows/upgrade-e2e.yml
Labels: backport, ready-to-test, maintenance

#815 Bump main module to K8s 0.24.2
  coredns/go.sum
  go.mod
  go.sum
  pkg/agent/controller/controller_suite_test.go
Labels: ready-to-test

#829 Automated backport of #807: Bump x/text to address CVE-2021-38561
  coredns/go.mod
  coredns/go.sum
  go.mod
  go.sum
Labels: ready-to-test, automated-backport

#838 Use minimal KIND clusters
  .shipyard.e2e.yml
Labels: ready-to-test

#836 Automated backport of #834: Run the upgrade job on devel only
  .github/workflows/upgrade-e2e.yml
Labels: ready-to-test, automated-backport

#835 Automated backport of #834: Run the upgrade job on devel only
  .github/workflows/upgrade-e2e.yml
Labels: ready-to-test, automated-backport
