Repository submariner-io/lighthouse, pull requests merged in 2022-03, with the labels that each got.

#699 Bump actions/checkout to v3
  .github/workflows/codeowners.yml
  .github/workflows/e2e-full.yml
  .github/workflows/e2e.yml
  .github/workflows/flake_finder.yml
  .github/workflows/linting.yml
  .github/workflows/periodic.yml
  .github/workflows/release.yml
  .github/workflows/unit.yml
  .github/workflows/upgrade-e2e.yml
Labels: ready-to-test

#700 Add packagedoc-lint linting, fix errors
  .github/workflows/linting.yml
  pkg/agent/controller/agent.go
  pkg/agent/controller/controller_suite_test.go
  pkg/agent/controller/endpoint.go
  pkg/agent/controller/global_ingressip_cache.go
  pkg/agent/controller/globalingressip.go
  pkg/agent/controller/globalnet_test.go
  pkg/agent/controller/headless_service_test.go
  pkg/agent/controller/reconciliation_test.go
  pkg/agent/controller/service_export_failures_test.go
  pkg/agent/controller/service_import_sync_test.go
  pkg/agent/controller/serviceimport.go
  pkg/agent/controller/types.go
  pkg/agent/main.go
  pkg/constants/constants.go
  pkg/coredns/main.go
  pkg/endpointslice/controller.go
  pkg/endpointslice/controller_test.go
  pkg/endpointslice/map.go
  pkg/endpointslice/map_test.go
  pkg/endpointslice/suite_test.go
  pkg/gateway/controller.go
  pkg/gateway/controller_test.go
  pkg/loadbalancer/balancer.go
  pkg/loadbalancer/smooth_weighted_round_robin.go
  pkg/loadbalancer/smooth_weighted_round_robin_test.go
  pkg/loadbalancer/suite_test.go
  pkg/service/controller.go
  pkg/serviceimport/controller.go
  pkg/serviceimport/controller_test.go
  pkg/serviceimport/map.go
  pkg/serviceimport/map_test.go
  pkg/serviceimport/store.go
  pkg/serviceimport/suite_test.go
  plugin/lighthouse/handler.go
  plugin/lighthouse/handler_test.go
  plugin/lighthouse/lighthouse.go
  plugin/lighthouse/metrics.go
  plugin/lighthouse/parse.go
  plugin/lighthouse/parse_internal_test.go
  plugin/lighthouse/plugin_suite_test.go
  plugin/lighthouse/record.go
  plugin/lighthouse/setup.go
  plugin/lighthouse/setup_internal_test.go
  test/e2e/discovery/headless_services.go
  test/e2e/discovery/service_discovery.go
  test/e2e/discovery/statefulsets.go
  test/e2e/framework/framework.go
Labels: automation, backport, ready-to-test

#701 Add packagedoc-lint linting, fix errors
  .github/workflows/linting.yml
  pkg/agent/controller/agent.go
  pkg/agent/controller/controller_suite_test.go
  pkg/agent/controller/endpoint.go
  pkg/agent/controller/global_ingressip_cache.go
  pkg/agent/controller/globalingressip.go
  pkg/agent/controller/globalnet_test.go
  pkg/agent/controller/headless_service_test.go
  pkg/agent/controller/reconciliation_test.go
  pkg/agent/controller/service_export_failures_test.go
  pkg/agent/controller/service_import_sync_test.go
  pkg/agent/controller/serviceimport.go
  pkg/agent/controller/types.go
  pkg/agent/main.go
  pkg/constants/constants.go
  pkg/coredns/main.go
  pkg/endpointslice/controller.go
  pkg/endpointslice/controller_test.go
  pkg/endpointslice/map.go
  pkg/endpointslice/map_test.go
  pkg/endpointslice/suite_test.go
  pkg/gateway/controller.go
  pkg/gateway/controller_test.go
  pkg/loadbalancer/balancer.go
  pkg/loadbalancer/smooth_weighted_round_robin.go
  pkg/loadbalancer/smooth_weighted_round_robin_test.go
  pkg/loadbalancer/suite_test.go
  pkg/service/controller.go
  pkg/serviceimport/controller.go
  pkg/serviceimport/controller_test.go
  pkg/serviceimport/map.go
  pkg/serviceimport/map_test.go
  pkg/serviceimport/store.go
  pkg/serviceimport/suite_test.go
  plugin/lighthouse/handler.go
  plugin/lighthouse/handler_test.go
  plugin/lighthouse/lighthouse.go
  plugin/lighthouse/metrics.go
  plugin/lighthouse/parse.go
  plugin/lighthouse/parse_internal_test.go
  plugin/lighthouse/plugin_suite_test.go
  plugin/lighthouse/record.go
  plugin/lighthouse/setup.go
  plugin/lighthouse/setup_internal_test.go
  test/e2e/discovery/headless_services.go
  test/e2e/discovery/service_discovery.go
  test/e2e/discovery/statefulsets.go
  test/e2e/framework/framework.go
Labels: ready-to-test

#705 Remove K8s 1.20 tests as it's EOL
  .github/workflows/e2e-full.yml
  .github/workflows/flake_finder.yml
Labels: automation, ready-to-test

#708 Update actions/upload-artifact from 2.2.4 to 3.0.0
  .github/workflows/unit.yml
Labels: automation, ready-to-test

#711 Only ignore Dockerfile.* in the root directory
  .gitignore
Labels: ready-to-test

#715 Only retain last state for condition types
  pkg/agent/controller/agent.go
  pkg/agent/controller/controller_suite_test.go
  pkg/agent/controller/globalnet_test.go
  pkg/agent/controller/service_export_failures_test.go
  pkg/agent/controller/service_import_sync_test.go
Labels: ready-to-test

#717 Fix flaky agent controller test
  pkg/agent/controller/endpoint.go
  pkg/agent/controller/serviceimport.go
  pkg/agent/controller/types.go
Labels: ready-to-test
