Repository submariner-io/lighthouse, pull requests merged in 2023-11, with the labels that each got.

#1420 Update grpc to fix GHSA-m425-mq94-257g CVE
  coredns/go.mod
  coredns/go.sum
Labels: ready-to-test, security

#1430 Delete stale EndpointSlices on restart
  pkg/agent/controller/agent.go
  pkg/agent/controller/endpoint_slice.go
  pkg/agent/controller/reconciliation_test.go
  pkg/agent/controller/service_endpoint_slices.go
  pkg/agent/controller/service_import.go
  pkg/agent/controller/types.go
Labels: backport, ready-to-test

#1432 Automated backport of #1430: Delete stale EndpointSlices on restart
  pkg/agent/controller/agent.go
  pkg/agent/controller/endpoint_slice.go
  pkg/agent/controller/reconciliation_test.go
  pkg/agent/controller/service_endpoint_slices.go
  pkg/agent/controller/service_import.go
  pkg/agent/controller/types.go
Labels: ready-to-test, release-note-needed, automated-backport

#1437 Override the ImageMagick license detection
  .lichen.yaml
Labels: ready-to-test

#1440 Automated backport of #1439: Fix invalid ServiceExport Conflict status condition
  pkg/agent/controller/clusterip_service_test.go
  pkg/agent/controller/controller_suite_test.go
  pkg/agent/controller/endpoint_slice.go
Labels: ready-to-test, release-note-needed, automated-backport

#1442 Switch from stale app to stale GHA
  .github/stale.yml
  .github/workflows/stale.yml
Labels: automation, ready-to-test

#1441 Remove helm from the flake finder
  .github/workflows/flake_finder.yml
Labels: ready-to-test

#1446 Retry ServiceImport check in check_nginx Makefile target
  Makefile
Labels: ready-to-test

#1444 Bump admiral and adjust to changes
  go.mod
  go.sum
  pkg/agent/controller/clusterip_service_test.go
  pkg/agent/controller/service_import.go
  pkg/agent/controller/service_import_aggregator.go
Labels: ready-to-test
