Repository submariner-io/lighthouse, pull requests merged in 2023-09, with the labels that each got.

#1359 Only release images on submariner-io
  .github/workflows/release.yml
Labels: automation, ready-to-test

#1386 Reinstate the submariner_service_export metric
  pkg/agent/controller/service_import.go
Labels: ready-to-test

#1387 Automated backport of #1386: Reinstate the submariner_service_export metric
  pkg/agent/controller/service_import.go
Labels: ready-to-test, automated-backport
