Repository submariner-io/lighthouse, pull requests merged in 2023-04, with the labels that each got.

#1182 Support for manual trigger of release image job
  .github/workflows/release.yml
Labels: ready-to-test

#1186 Fix panic in AfterEach when test is skipped
  test/e2e/discovery/service_discovery.go
Labels: backport, ready-to-test

#1188 Automated backport of #1186: Fix panic in AfterEach when test is skipped
  test/e2e/discovery/service_discovery.go
Labels: ready-to-test, automated-backport

#1189 Cache images for E2E
  .github/workflows/e2e-full.yml
  .github/workflows/e2e.yml
Labels: ready-to-test

#1190 Use BeNumerically for numeric comparisons in tests
  .golangci.yml
  test/e2e/discovery/service_discovery.go
Labels: ready-to-test

#1192 Adjust to renamed syncer fields
  go.mod
  go.sum
  pkg/agent/controller/endpoint_slice.go
Labels: ready-to-test

#1191 Specify that E2E needs the images step
  .github/workflows/e2e.yml
Labels: ready-to-test

#1193 Automated backport of #1189: Cache images for E2E
  .github/workflows/e2e-full.yml
  .github/workflows/e2e.yml
Labels: dependent, ready-to-test, automated-backport

#1194 Configure dependabot for the release-0.15 branch
  .github/dependabot.yml
Labels: ready-to-test

#1195 [0.14] Bump tim-actions GHAs for node updates
  .github/workflows/linting.yml
Labels: ready-to-test

#1196 [0.13] Bump tim-actions GHAs for node updates
  .github/workflows/linting.yml
Labels: ready-to-test
