Repository submariner-io/lighthouse, pull requests merged in 2023-02, with the labels that each got.

#1088 Bump to coredns 1.10.1
  coredns/go.mod
  coredns/go.sum
Labels: dependencies, ready-to-test

#1087 Remove unused "cluster-ip" annotation for ServiceImport
  pkg/agent/controller/agent.go
Labels: technical-debt, ready-to-test

#1085 Handle migration of ServiceImport labels
  coredns/serviceimport/map.go
  coredns/serviceimport/map_test.go
Labels: ready-to-test

#1086 Properly disable gateway controller in SD-only install
  coredns/gateway/controller.go
  coredns/gateway/controller_test.go
  coredns/plugin/setup_internal_test.go
Labels: ready-to-test

#1091 Remove unused key field in Info structs
  coredns/endpointslice/map.go
  coredns/serviceimport/map.go
Labels: technical-debt, ready-to-test

#1102 Bump golang.org/x/net to 0.7.0
  coredns/go.mod
  coredns/go.sum
  go.mod
  go.sum
Labels: ready-to-test

#1111 Ignore "not ready" addresses for EndpointSlices
  coredns/endpointslice/map.go
  coredns/endpointslice/map_test.go
  pkg/agent/controller/controller_suite_test.go
  pkg/agent/controller/endpoint.go
  pkg/agent/controller/headless_service_test.go
Labels: ready-to-test
