Repository submariner-io/lighthouse, pull requests merged in 2024-04, with the labels that each got.

#1536 Update protobuf to 1.33.0 for GO-2024-2611
  coredns/go.mod
  coredns/go.sum
  go.mod
  go.sum
Labels: ready-to-test, security

#1535 Update protobuf to 1.33.0 for GO-2024-2611
  coredns/go.mod
  coredns/go.sum
  go.mod
  go.sum
Labels: ready-to-test, security

#1538 Use shipyard framework By instead of ginkgo By
  test/e2e/discovery/headless_services.go
  test/e2e/discovery/service_discovery.go
  test/e2e/discovery/statefulsets.go
  test/e2e/framework/framework.go
  test/e2e/internal/service_discovery.go
Labels: ready-to-test

#1528 Automated backport of #1521: Add cluster name to aggregated SI status on local SI creation
  pkg/agent/controller/headless_service_test.go
  pkg/agent/controller/service_import.go
  pkg/agent/controller/service_import_aggregator.go
Labels: ready-to-test, release-note-needed, automated-backport

#1540 Update quic-go to 0.42.0 for CVE-2024-22189
  coredns/go.mod
  coredns/go.sum
Labels: ready-to-test, security

#1543 Update protobuf to 1.33.0 for CVE-2024-24786
  coredns/go.mod
  coredns/go.sum
  go.mod
  go.sum
Labels: ready-to-test, security

#1541 Update quic-go to 0.42.0 for CVE-2024-22189
  coredns/go.mod
  coredns/go.sum
Labels: ready-to-test, security

#1542 Update protobuf to 1.33.0 for CVE-2024-24786
  coredns/go.mod
  coredns/go.sum
  go.mod
  go.sum
Labels: ready-to-test, security
