Repository submariner-io/lighthouse, pull requests merged in 2024-08, with the labels that each got.

#1614 Remove dependabot config for release 0.14
  .github/dependabot.yml
Labels: ready-to-test

#1615 Use log.Debugf to format instead of fmt.Sprintf
  coredns/plugin/handler.go
Labels: ready-to-test

#1612 Bump admiral to pull in K8s v0.31.0 and adjust
  coredns/gateway/controller.go
  coredns/go.mod
  coredns/go.sum
  go.mod
  go.sum
Labels: ready-to-test

#1622 Fix sporadic failure in resolver migration unit test
  coredns/resolver/migration_test.go
Labels: ready-to-test

#1621 Propagate exported Service session affinity to ServiceImport
  pkg/agent/controller/agent.go
  pkg/agent/controller/clusterip_service_test.go
  pkg/agent/controller/controller_suite_test.go
  pkg/agent/controller/service_import.go
Labels: ready-to-test

#1625 Remove broker resync period for ServiceImport and EndpointSlices
  pkg/agent/controller/endpoint_slice.go
  pkg/agent/controller/service_import.go
  pkg/agent/controller/types.go
Labels: backport, ready-to-test

#1628 Automated backport of #1625: Remove broker resync period for ServiceImport and
  pkg/agent/controller/controller_suite_test.go
  pkg/agent/controller/endpoint_slice.go
  pkg/agent/controller/service_import.go
  pkg/agent/controller/types.go
Labels: ready-to-test, release-note-needed, automated-backport

#1627 Automated backport of #1625: Remove broker resync period for ServiceImport and
  pkg/agent/controller/endpoint_slice.go
  pkg/agent/controller/service_import.go
  pkg/agent/controller/types.go
Labels: ready-to-test, release-note-needed, automated-backport

#1626 Automated backport of #1625: Remove broker resync period for ServiceImport and
  pkg/agent/controller/endpoint_slice.go
  pkg/agent/controller/service_import.go
  pkg/agent/controller/types.go
Labels: ready-to-test, release-note-needed, automated-backport
