Repository submariner-io/lighthouse, pull requests merged in 2024-03, with the labels that each got.

#1514 Add dependabot config for release-0.17
  .github/dependabot.yml
Labels: ready-to-test

#1517 Only fail builds for high+ vulns
  .github/workflows/linting.yml
Labels: backport, ready-to-test

#1523 Automated backport of #1517: Only fail builds for high+ vulns
  .github/workflows/linting.yml
Labels: ready-to-test, automated-backport

#1525 Automated backport of #1517: Only fail builds for high+ vulns
  .github/workflows/linting.yml
Labels: ready-to-test, automated-backport

#1522 Automated backport of #1517: Only fail builds for high+ vulns
  .github/workflows/linting.yml
Labels: ready-to-test, automated-backport

#1524 Automated backport of #1517: Only fail builds for high+ vulns
  .github/workflows/linting.yml
Labels: ready-to-test, automated-backport

#1526 Automated backport of #1498: Use the Admiral metrics/profile helper and enable profiling
  go.mod
  go.sum
  pkg/agent/main.go
Labels: ready-to-test, automated-backport
