Repository submariner-io/lighthouse, pull requests merged in 2025-07, with the labels that each got.

#1783 Bump Kubernetes to 1.33
  .golangci.yml
  coredns/go.mod
  coredns/go.sum
  go.mod
  go.sum
Labels: ready-to-test

#1834 Use named Kubernetes versions in GHAs
  .github/workflows/e2e.yml
  .github/workflows/flake_finder.yml
Labels: backport, ready-to-test

#1856 Automated backport of #1834: Use named Kubernetes versions in GHAs
  .github/workflows/e2e.yml
  .github/workflows/flake_finder.yml
Labels: ready-to-test, automated-backport

#1855 Automated backport of #1834: Use named Kubernetes versions in GHAs
  .github/workflows/e2e.yml
  .github/workflows/flake_finder.yml
Labels: ready-to-test, automated-backport

#1853 Automated backport of #1834: Use named Kubernetes versions in GHAs
  .github/workflows/e2e.yml
  .github/workflows/flake_finder.yml
Labels: ready-to-test, automated-backport

#1863 Apply ServiceExport Conflict condition on all exporting clusters
  .github/workflows/e2e.yml
  pkg/agent/controller/agent.go
  pkg/agent/controller/cleanup_test.go
  pkg/agent/controller/clusterip_service_test.go
  pkg/agent/controller/controller_suite_test.go
  pkg/agent/controller/endpoint_slice.go
  pkg/agent/controller/reconciliation_test.go
  pkg/agent/controller/service_export_client.go
  pkg/agent/controller/service_export_failures_test.go
  pkg/agent/controller/service_import.go
  pkg/agent/controller/service_import_aggregator.go
  pkg/agent/controller/service_import_conflict.go
  pkg/agent/controller/types.go
  pkg/constants/constants.go
Labels: ready-to-test
